# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
framework:
    secret: '%env(APP_SECRET)%'
    deprecations:
        enabled: true
        max_items: '%env(SYMFONY_DEPRECATIONS_HELPER)%'
    session: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
