version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin   # Mot de passe root pour MySQL
      MYSQL_DATABASE: mydatabase  # Nom de la base de données à créer
      MYSQL_USER: admin           # Nom de l'utilisateur MySQL
      MYSQL_PASSWORD: admin       # Mot de passe de l'utilisateur MySQL
    command: ['--default-authentication-plugin=mysql_native_password']
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
