version: '3.8'

services:
  database:
    image: postgres:${{ env.POSTGRES_VERSION }}-alpine
    environment:
      POSTGRES_DB: ${{ env.POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_USER: ${{ env.POSTGRES_USER }}
    volumes:
      - database_data:/var/lib/postgresql/data

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  database_data:
